TRUNCATE TABLE POKEMON;

INSERT INTO POKEMON (ID, NAME)
    VALUES (1, 'Bulbasaur');
INSERT INTO POKEMON (ID, NAME)
    VALUES (2, 'Ivysaur');
INSERT INTO POKEMON (ID, NAME)
    VALUES (3, 'Venasaur');
INSERT INTO POKEMON (ID, NAME)
    VALUES (4, 'Squirtle');
INSERT INTO POKEMON (ID, NAME)
    VALUES (5, 'Wartortle');
INSERT INTO POKEMON (ID, NAME)
    VALUES (6, 'Blastoise');
INSERT INTO POKEMON (ID, NAME)
    VALUES (7, 'Charmander');
INSERT INTO POKEMON (ID, NAME)
    VALUES (8, 'Charmeleon');
INSERT INTO POKEMON (ID, NAME)
    VALUES (9, 'Charizard');
